language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "iJq3ORK+kM/vScVbXOKOlQHSy2wJesd/AFnUrluRMKi4bGRRK+Ut4wPDOGs2Btl8UrZ6ZEWGiwdj+Er9YMv9V9ygHyKvsMZC8Ov6DDJtxm12SUmzRTc2ItAqTYh0S0WE29rf6NjIzuefCYJjWQTwlt27j9C2xxt2L7Bs3blxgD1x5HZny07z8xlRFl5w8Hqz9xFFwglVz/yJS62BwmKSBSHrNpnZpHMqAGY0vWuF7DDZq6wfidi7Y1DD6FlO45N+yLFkl4/EKioxA/gabUCVaryVldSxo+WOQUA8/2v5M2KgULZ3watohJezrDQX3rZUfsshVYDCHV2SPcDi114EbXzGavt8vDRde9jPQTuotBkdA7UbtJWvIoY9GVRLcpLNcfm1ArpfGeX88UCazVqs0TeChLdsK2NbVTByz0PClxLz7hn+YK64kOj1NfgadJ0We32/mSD5A+bog07AEYvOJM2K/8uTVfKiD0hZ20PLmOIVFmWSg+kHUo8DlKN4GMZ2DesOuBqzBqOX5ofznDR/BEmxkbFbj3mTHg5aXRtdhVs3spgjS09AX556UXdD2L25GdylnL4qRPRnwIl3eHXKEHQ3xU85Xm1dLCTY1ED/wXtwLVvqwwdM36vK4c3pMzzDI1Z+Ul5eZfqj3up62mxzvK5M+5RHrlCYMPwF37CBDeE="
  - secure: "FYUqOSwyeW4oeNVkO1JDCM9A1MrsmUGLx3S5ZEiPc7LqRgw4zSuQ48ze/Lz0z/30OygB2sj5KYs2Op7N4DjzycK2EYVsAzuz17cSGRWCh9cPedKcTLqU+BHpZCcYQyehg2qre+s5Xka7VwFGK7mX4hKQ8iIaX5QcR5Z+bIH4D7OB1BMZnGDxZ8S3ZWsKa4cPdiXqOKjbcZQShrD9tUOAhoeJ7h3kJKfvBmHizlHgXe+Iw+kx/qGR0vh05O2aF1ADXz4K+V4G8oeTOqOnUchFxQg7nquUX+Cw345DxxrCQAUWcQFhbV0rhS1ejeWzBsIQcxSTJ6hLnHvNv29H5Lj+I1Xek5ZAE7chcy58zt/HbQUfL9YAllNxXR7llvEegUP7SvtPTU4tSUvOlqRqrhQY9cnqslp8NMVmhPRVHp0ZWJWH+qYSjOLKFNsVYGd4YEWuwRIKyw6NIr2yaN8U2YD4kQzHCCDXwcOCXOJ4YvRoqMWy6iOvKFcgjtSUnwTDkkxDuFFxGJcMItCbqMdh3Gk3PG5pc1IBEy3+PNUnZzHbkBXOi+ZnLT29W0uTzPOSkFGnX1oseHN4cWm5Vz5XO+n+5Sp0DDZV1osAkO6PsXPwiobZkxOFD/Rq/0moHFv16VJkds1cn2A3bREYKQmw12/y3O7UPB5GdgLPY+0zV9vyrTE="
  - secure: "iiHpY8xL5/8c8Aou2TOSZtUdkRIUqBss5d2Ch4Eiw6i2MkeouZatT8Jz3zTi8ecZsshvuI3AIrvCvmpG4b41YJjomuVFVto2BaMlbT1CuOnMHuiBs2LspJSKgTlbXL+xw+uIgxD/N2lZBzctldpVNd0Ask8KXwazEqQLDgc2Z2pEGlkq+WVhEUa5Z65I+KTj5trAmDRhnwp1zSqrWvaTKuJ2QR1zTRJ/df9C3IEQGab36ByWF5d/Ta/TRVF31kTt2XxF8kpYpLhoT6IcKmV+fbzdQmppVG3xB/bthE0klPF/rMYMuvFfuR1HKWcCQKIB/pv3aMYooDFVOYN/kXijzavAFrLHk+tFTW3NUq691GeT9ENjE/5KN+PrKHkTVLwaWmVm2Rdv/rUcSVSmZCFfbsCORiol/60c+tUQdqeuamCxeGzKLf450/nYZ+Q5n7+l0Shaka4q0IXDdi5LXZ281pVDSzw+Jq7O9SsyssMIWX+0UvwkxtgJWI0/R3R52D6Gml9LbZ8Y7l4A5lrKv3Jxuc5ZHzJR4n9pnQQTKhScYENesS5nKwILUFBsoOOejhnlONnhSTvkqzLifXGJCy0SxnaQcNIhlA3ktraRfEZaDwuxnzrAtmWQPKnSICKjdHxUeWL5NUda/xSzekGiVz2XabI62sa7Or/DTkoVXIBwXH0="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_2a1418006778_key -iv $encrypted_2a1418006778_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi